<div style="display: flex; flex-direction: column">
    <a href="index.php">Главная</a>
    <a href="about.php">О нас</a>
    <a href="delivery.php">Доставка</a>
    <a href="warranty.php">Гарантия</a>
    <a href="reviews.php">Отзывы</a>
    <a href="faq.php">Частые вопросы</a>
    <a href="faq-detail.php">Вопрос детально</a>
    <a href="blog.php">Блог</a>
    <a href="blog-detail.php">Статья блога</a>
    <a href="contacts.php">Контакты</a>
    <a href="404.php">404</a>
    <a href="paper-pens.php">Бумажные ручки Лендинг</a>
    <a href="scratch.php">Когтеточки</a>
    <a href="login.php">Вход в ЛК</a>
    <a href="lk.php">Ваш менеджер</a>
    <a href="orders.php">Заказы</a>
    <a href="personal-info.php">Информация</a>
    <a href="requisites.php">Реквизиты</a>
    <a href="register.php">Регистрация</a>
</div>